Repository sachin235/HacktoberFest101, pull requests merged in 2022-10, with the labels that each got.

#245 Combination sum II
  Python/recursion/combination sum
Labels: hacktoberfest-accepted

#230 Find the middle number in linked list #223
  C++/LinkedList/MiddleNumberLL.cpp
Labels: changes-required

#225 Mersenne Prime Number
  MersennePrime.java
Labels: changes-requested

#267 feat: added inOrder traversal
  C++/Binary Tree/inOrderTraversal.cpp
Labels: changes-requested
